### ISSUE TITLE
Collect user feedback and promote the Constitution Checker

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/constitution-checker#58]
- [x]  Prepare for usability testing interviews 
- [x]  Send message to Discord GovTools channel
- [x] Reach out to Voltaire team for feedback
- [x] Reach out to Intersect for feedback
- [x]  Reach out to internal employees get usability testers and feedback
- [x] Get tool listed on Sanchonet docs and Essential Cardano
- [x] GovTools working group demo
- [x] 2 Usability testing interviews (Ivan, Ian)
- [x] Summarize feedback and deliver to project stakeholders

**Comment by robpangilinanioi** [comment]
On-going discussions

**Comment by KJES4** [comment]
I've reached out to multiple people on the Voltaire team to collect feedback and to get input on how to promote this tool. I've also tried to gather feedback from Intersect directly. I've reached out to a few other people to see if they can participate in user testing. 

The only thing I was told, so far, from a designer at Intersect is that he likes the design and thinks the application is great because the UI is designed to be simple to understand.

**Comment by KJES4** [comment]
Created a [PR](https://github.com/input-output-hk/sanchonet/pull/160) to have this tool listed on the [Sanchonet docs](https://sancho.network/tools-resources/resources/).

**Comment by KJES4** [comment]
I was able to get 2 volunteers to take part in some usability testing. I will interview them next week.

**Comment by KJES4** [comment]
Next steps:
Incorporate user feedback: https://github.com/input-output-hk/constitution-checker/issues/86
Final promotion and educational work after updates: https://github.com/input-output-hk/constitution-checker/issues/87
